[package]
name = "future-mpsc-example"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]
tokio-core = "0.1.4"
futures = "0.1.10"
env_logger = "0.4.1"
log = "0.3.6"
